### ISSUE TITLE
I can not download file from device to host machine.

### ISSUE THREAD

**Issue by majdarov** [BoresXP/nodemcu-tools#1]
NodeMCU-ESP8266, file - init.lua.
There is a download notification hanging, but nothing happens...
![image](https://github.com/BoresXP/nodemcu-tools/assets/56847952/6948a6c1-13eb-4325-9788-ee0abead9342)

>  VS Code
    Версия: 1.83.1 (user setup)
    Фиксация: f1b07bd25dfad64b0167beb15359ae573aecd2cc
    Дата: 2023-10-10T23:48:05.904Z
    Electron: 25.8.4
    ElectronBuildId: 24154031
    Chromium: 114.0.5735.289
    Node.js: 18.15.0
    V8: 11.4.183.29-electron.0
    ОС: Windows_NT x64 10.0.19045

**Comment by serg3295** [comment]
1. The user's program should not be executed on the ESP at the time of downloading the file. Since print( ) from the program to the console may interfere.

2. Check if there is a Russian letter 'a' in the init.lua file name.

**Comment by serg3295** [comment]
Possibly related to issue #4
