### ISSUE TITLE
Can't upload or download file

### ISSUE THREAD

**Issue by zdila** [BoresXP/nodemcu-tools#4]
On upload I see this forever: _Uploading init.lua to NodeMCU@/dev/ttyUSB0_

Same for download.

Listing files, execuding commands via prompt works.

`nodemcu-uploader upload init.lua` also works.

I use latest vscode and nodemcu-tools on Linux with ESP32 Development Board - DEVKIT V1.

**Comment by serg3295** [comment]
which version of esp32 firmware is used? Please, provide nodemcu startup banner.

EDIT:
btw, only `init.lua` does not upload, or any file does not upload either?

**Comment by zdila** [comment]
<details>
<summary>Boot Message</summary>

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6772
load:0x40078000,len:11172
ho 0 tail 12 room 4
load:0x40080400,len:5892
entry 0x400806f8
I (70) boot: Chip Revision: 1
I (71) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (42) boot: ESP-IDF v3.3-beta2-1234-gb64b375234 2nd stage bootloader
I (42) boot: compile time 11:43:00
I (43) boot: Enabling RNG early entropy source...
I (48) boot: SPI Speed      : 40MHz
I (52) boot: SPI Mode       : DIO
I (56) boot: SPI Flash Size : 4MB
I (61) boot: Partition Table:
I (64) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (86) boot:  2 factory          factory app      00 00 00010000 00180000
I (94) boot:  3 lfs              unknown          c2 01 00190000 00010000
I (101) boot:  4 nodemcuspiffs    unknown          c2 00 001a0000 00070000
I (109) boot: End of partition table
I (113) boot_comm: chip revision: 1, min. application chip revision: 0
I (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2aaa8 (174760) map
I (188) esp_image: segment 1: paddr=0x0003aad0 vaddr=0x3ffb0000 size=0x03610 ( 13840) load
I (194) esp_image: segment 2: paddr=0x0003e0e8 vaddr=0x40080000 size=0x00400 (  1024) load
I (196) esp_image: segment 3: paddr=0x0003e4f0 vaddr=0x40080400 size=0x01b20 (  6944) load
I (207) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0xaa778 (698232) map
I (449) esp_image: segment 5: paddr=0x000ea798 vaddr=0x40081f20 size=0x141fc ( 82428) load
I (481) esp_image: segment 6: paddr=0x000fe99c vaddr=0x400c0000 size=0x00064 (   100) load
I (495) boot: Loaded app from partition at offset 0x10000
I (495) boot: Disabling RNG early entropy source...
I (496) cpu_start: Pro cpu up.
I (499) cpu_start: Application information:
I (504) cpu_start: Project name:     NodeMCU
I (509) cpu_start: App version:      0294835-dirty
I (515) cpu_start: Compile time:     Oct  4 2024 11:43:03
I (521) cpu_start: ELF file SHA256:  c727196c4dc9f42d...
I (527) cpu_start: ESP-IDF:          v3.3-beta2-1234-gb64b375234
I (533) cpu_start: Starting app cpu, entry point is 0x400813c8
I (0) cpu_start: App cpu up.
I (544) heap_init: Initializing. RAM available for dynamic allocation:
I (551) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (557) heap_init: At 3FFB9C80 len 00026380 (152 KiB): DRAM
I (563) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (569) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (576) heap_init: At 4009611C len 00009EE4 (39 KiB): IRAM
I (582) cpu_start: Pro cpu start user code
I (265) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.

Mounting flash filesystem...
Flash sig not correct: 65536 vs 4210729296
I (405) wifi:wifi driver task: 3ffc4918, prio:23, stack:3584, core=0
I (405) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (405) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (435) wifi:wifi firmware version: 74b0970
I (435) wifi:config NVS flash: enabled
I (435) wifi:config nano formating: disabled
I (435) wifi:Init dynamic tx buffer num: 32
I (445) wifi:Init data frame dynamic rx buffer num: 32
I (445) wifi:Init management frame dynamic rx buffer num: 32
I (455) wifi:Init management short buffer num: 32
I (455) wifi:Init static rx buffer size: 1600
I (465) wifi:Init static rx buffer num: 10
I (465) wifi:Init dynamic rx buffer num: 32

NodeMCU ESP32 built on nodemcu-build.com provided by frightanic.com
	branch: dev-esp32-idf3-final
	commit: 0294835c0243f69bba733961fb0e2642dbcb6f63
	SSL: true
	modules: bit,dac,encoder,file,gpio,http,i2c,ledc,mqtt,net,node,sjson,spi,tmr,uart,wifi
 build 2024-10-04-11-42-58 powered by Lua 5.1.4 on ESP-IDF v3.3-beta1-1738-gb64b375234 on SDK IDF
hello world
>
```
</details>


<details>
<summary>NodeMCU Firmware</summary>
Your NodeMCU custom build finished successfully. You may now download the firmware:
- float: https://nodemcu-build.com/builds/nodemcu-dev-esp32-idf3-final-16-modules-2024-10-04-11-42-58-float.bin
- integer: https://nodemcu-build.com/builds/nodemcu-dev-esp32-idf3-final-16-modules-2024-10-04-11-42-58-integer.bin

This was built against the dev-esp32-idf3-final branch and includes the following modules: bit, dac, encoder, file, gpio, http, i2c, ledc, mqtt, net, node, sjson, spi, tmr, uart, wifi.
The files are guaranteed to be available for download for 24h.

I invite you to try my standalone desktop tool to flash firmware binaries: https://github.com/marcelstoer/nodemcu-pyflasher

Learn how to flash the firmware: https://nodemcu.readthedocs.io/en/dev-esp32-idf3-final/flash/. If you're upgrading from a previous version you should carefully study the "Upgrading Firmware" instructions on that page.

Please help keep this service alive: http://nodemcu-build.com/faq.php#support
</details>

**Comment by zdila** [comment]
> btw, only init.lua does not upload, or any file does not upload either?

Tried now also `test.txt` with `Hello world!` and the problem was the same.

**Comment by serg3295** [comment]
Thanks.

Unfortunately, the cloud build service only builds firmware for the `esp32-idf3` branch. `-idf3` is a very old branch.

I recommend building the firmware yourself as described in the[ nodemcu.io documentation](https://nodemcu.readthedocs.io/en/dev-esp32/build/). 
The latest `dev-esp32` branch includes many bug fixes and new features.

I don't have esp32-devkit at hand, so I won't be able to look at the issue until next week.
Nevertheless, it seems a bug, and should  be fixed.

Yet another question. What esp type is displayed in the status bar after connection?
![05-10-24_08-08](https://github.com/user-attachments/assets/549d95f9-3e39-452e-838d-0c6d9d927c1f)

**Comment by zdila** [comment]
Thank you. I will try different firmware.

![image](https://github.com/user-attachments/assets/141fa18f-8093-41e0-894f-17791c4d65de)

**Comment by serg3295** [comment]
I just remembered why the extension does not work with `esp32-idf3` branch.
The stale `esp32-idf3` branch uses nodemcu 'file' module to perform file operations.
Newer esp32 firmware uses Lua `io` module for that.

Until recently, the cloud build service did not support building firmware for esp32 at all and users had to build firmware from source.

I deliberately did not support the stale esp32-idf3 branch, since it is better to build newer version from source.

I'll add support for the outdated idf3 firmware to the extension, so that newbies in nodemcu can start working with the Nodemcu Lua ecosystem.
However, I strongly recommend using the newer esp32 firmware.

**Comment by zdila** [comment]
Tested with the manually cloned and built NodeMCU for ESP32 and it works! Thank you for the assistance and feel free to close the issue.

**Comment by serg3295** [comment]
I have added support for the `-idf3` branch, because not everyone can build the firmware from sources, especially Windows user.
