### ISSUE TITLE
Empty tab after press "Connect" button

### ISSUE THREAD

**Issue by imareo** [BoresXP/nodemcu-tools#6]
fedora 41, vscode 1.96.2, nodejs via nvm 20.18.1
try versions plugins - 4.5.0 and 4.6.0

after press "Connect" button open new tab NodeMCU@/dev/ttyUSB0, blink buttons at bottom screen and then contents are cleared.

**Comment by serg3295** [comment]
I guess that the esp was incorrectly flashed.

Try connecting to the esp using any terminal program and see the output. Or you can view the log by pressing ctrl+shift+P => Developer: Toggle Developer Tools => Console
I think the esp is continuously rebooting.

**Comment by imareo** [comment]
![image](https://github.com/user-attachments/assets/fb318746-d8e2-41bd-aff5-85358cca7e25)
console after press reset on board. 
atm can't reflash, add comment later

**Comment by serg3295** [comment]
If **atm** means 'Automatic Teller Machine' , I don't understand what `nodemcu-tools` has to do with it?
The extension is intended to interact with the [ESP32](https://www.espressif.com/en/products/socs/esp32) and [ESP8266](https://www.espressif.com/en/products/socs/esp8266) WiFi SOCs from Espressif flashed with[ NodeMCU Lua ](https://nodemcu.readthedocs.io/en/release/)firmware

**Comment by imareo** [comment]
oh... sorry
atm - at the moment

upd. after flash new firmware no problem now
